<?php

return [
    'rule.default' => ':attribute tidak valid.',
    'rule.alpha' => ':attribute harus berupa huruf.',
    'rule.alpha_dash' => ':attribute harus berupa huruf, angka, dan garis bawah.',
    'rule.alpha_spaces' => ':attribute harus berupa huruf, angka, dan spasi.',
    'rule.array' => ':attribute harus berupa array.',
    'rule.date' => ':attribute harus berupa tanggal.',
    'rule.datetime' => ':attribute harus berupa tanggal dan waktu.',
    'rule.digits' => ':attribute harus terdiri dari :length digit.',
    'rule.email' => ':attribute harus berupa alamat email yang valid.',
    'rule.exists' => ':attribute tidak valid.',
    'rule.file' => ':attribute harus berupa file.',
    'rule.image' => ':attribute harus berupa gambar.',
    'rule.max' => ':attribute harus terdiri dari maksimal :max karakter.',
    'rule.mimes' => ':attribute harus berupa file berformat :values.',
    'rule.min' => ':attribute harus terdiri dari minimal :min karakter.',
    'rule.numeric' => ':attribute harus berupa angka.',
    'rule.required' => ':attribute harus diisi.',
    'rule.string' => ':attribute harus berupa string.',
    'rule.unique' => ':attribute telah terdaftar.',
    'rule.uploaded_file' => ':attribute harus berupa file terupload.',
    'rule.person_name' => ':attribute harus berupa nama yang valid.',
    'rule.same' => ':attribute harus sama dengan :field.',
];
